name: tf
channels:
  - defaults
dependencies:
  - python=3.7.6
  - pip=19.2.3
  - pip:
    - absl-py==0.12.0
    - astunparse==1.6.3
    - cached-property==1.5.2
    - cachetools==4.2.1
    - certifi==2020.12.5
    - chardet==4.0.0
    - cloudpickle==1.3.0
    - cycler==0.10.0
    - decorator==5.0.6
    - dm-control==0.0.364896371
    - dm-env==1.4
    - dm-tree==0.1.5
    - future==0.18.2
    - gast==0.3.3
    - glfw==2.1.0
    - google-auth==1.28.0
    - google-auth-oauthlib==0.4.4
    - google-pasta==0.2.0
    - grpcio==1.37.0
    - gym==0.18.0
    - h5py==2.10.0
    - idna==2.10
    - importlib-metadata==3.10.0
    - joblib==1.0.1
    - Keras-Preprocessing==1.1.2
    - kiwisolver==1.3.1
    - labmaze==1.0.4
    - lxml==4.6.3
    - Markdown==3.3.4
    - matplotlib==3.4.1
    - numpy==1.19.5
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - pandas==1.2.3
    - Pillow==7.2.0
    - protobuf==3.15.7
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyglet==1.5.0
    - PyOpenGL==3.1.5
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2021.1
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scipy==1.4.1
    - six==1.15.0
    - tensorboard==2.2.2
    - tensorboard-plugin-wit==1.8.0
    - tensorflow-estimator==2.2.0
    - tensorflow-gpu==2.2.0
    - tensorflow-probability==0.10.0
    - termcolor==1.1.0
    - tqdm==4.60.0
    - typing-extensions==3.7.4.3
    - urllib3==1.26.4
    - Werkzeug==1.0.1
    - wrapt==1.12.1
    - zipp==3.4.1
